services:
  postgres:
    container_name: wallet-postgres-db
    image: postgres:13-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-wallet_db_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-wallet_db_password}
      POSTGRES_DB: ${DB_NAME:-wallet_db}
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - wallet_postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "wal_level=logical"]
    networks:
      - wallet-network

  pgadmin:
    container_name: wallet-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - wallet_pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge

volumes:
  wallet_postgres_data:
    name: wallet_postgres_data
  wallet_pgadmin_data:
    name: wallet_pgadmin_data