server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prd
  datasource:
    url: ${DB_JDBC_URL:jdbc:postgresql://localhost:5432/wallet_db}
    username: ${DB_USERNAME:wallet_db_user}
    password: ${DB_PASSWORD:wallet_db_password}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        types:
          jackson:
            object:
              mapper: com.syneronix.wallet.spring.CustomObjectMapperSupplier
        hbm2ddl:
          create_namespaces: true
        jdbc:
          time_zone: UTC
          batch_size: 30
          batch_versioned_data: true
        temp:
          use_jdbc_metadata_defaults: true
        order_inserts: true
        order_updates: true
        show_sql: false
        use_sql_comments: false
        format_sql: true
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        default_schema: syneronix
  flyway:
    enabled: true
  sql:
    init:
      platform: postgres
      continue-on-error: false

syneronix:
  flyway:
    locations: classpath:db/migration
    flyway-environment: ${environment:prd}
  policy:
    rate-limit:
      max-transactions: 5
      window-minutes: 1

logging:
  config: classpath:logback-spring.xml


springdoc:
  override-with-generic-response: false
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    urlsPrimaryName: all
